# Generated by Django 5.2.7 on 2025-10-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craftsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأسطى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'أسطى',
                'verbose_name_plural': 'الأسطوات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العامل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CraftsmanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='أمتار')),
                ('orders', models.CharField(max_length=200, verbose_name='طلبات')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='main.craftsman', verbose_name='الأسطى')),
            ],
            options={
                'verbose_name': 'صف الأسطى',
                'verbose_name_plural': 'صفوف الأسطوات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='المكان')),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الأمتار')),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='واصل')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الباقي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='main.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'صف العميل',
                'verbose_name_plural': 'صفوف العملاء',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التصفية')),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الواصل')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الباقي')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='main.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'صف العامل',
                'verbose_name_plural': 'صفوف العمال',
                'ordering': ['order', 'id'],
            },
        ),
    ]
