# Generated by Django 5.2.7 on 2025-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_date_and_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsmanrow',
            name='date',
            field=models.DateField(blank=True, default='لا يوجد', null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='craftsmanrow',
            name='type',
            field=models.CharField(blank=True, default='لا يوجد', max_length=200, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='customerrow',
            name='date',
            field=models.DateField(blank=True, default='لا يوجد', null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='customerrow',
            name='type',
            field=models.CharField(blank=True, default='لا يوجد', max_length=200, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='workerrow',
            name='date',
            field=models.DateField(blank=True, default='لا يوجد', null=True, verbose_name='التاريخ'),
        ),
    ]
