# Generated by Django 5.0.14 on 2025-11-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_craftsmanrow_date_alter_craftsmanrow_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactoryRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="واصل"
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مصاريف",
                    ),
                ),
                (
                    "goods",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="بضاعة"
                    ),
                ),
                (
                    "outgoing",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="صادر"
                    ),
                ),
                (
                    "incoming",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="وارد"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default="لا يوجد", null=True, verbose_name="التاريخ"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
            ],
            options={
                "verbose_name": "صف المصنع",
                "verbose_name_plural": "صفوف المصنع",
                "ordering": ["order", "id"],
            },
        ),
    ]
