# Generated by Django 5.0.14 on 2025-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_factoryrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factoryrow",
            name="incoming",
        ),
        migrations.RemoveField(
            model_name="factoryrow",
            name="outgoing",
        ),
        migrations.AddField(
            model_name="factoryrow",
            name="note",
            field=models.CharField(
                default="لا يوجد", max_length=200, verbose_name="ملاحظة"
            ),
        ),
        migrations.AddField(
            model_name="factoryrow",
            name="statement",
            field=models.CharField(
                default="لا يوجد", max_length=200, verbose_name="بيان"
            ),
        ),
    ]
