# Generated by Django 5.0.14 on 2025-11-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_factoryrow_incoming_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrow",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="السعر"
            ),
        ),
    ]
