# Generated by Django 5.0.14 on 2025-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_customerrow_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrow",
            name="meters",
        ),
        migrations.RemoveField(
            model_name="customerrow",
            name="price",
        ),
        migrations.RemoveField(
            model_name="customerrow",
            name="type",
        ),
        migrations.AddField(
            model_name="customerrow",
            name="insulator_meters",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="أمتار العازل"
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="insulator_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="سعر العازل"
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="repairs",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="مرمات"
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="selek_meters",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="أمتار السيليكات",
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="selek_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="سعر السيليكات"
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="tex_meters",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="أمتار التكس"
            ),
        ),
        migrations.AddField(
            model_name="customerrow",
            name="tex_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="سعر التكس"
            ),
        ),
    ]
