# Generated by Django 5.0.14 on 2025-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_customerrow_meters_remove_customerrow_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrow",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="خصم"
            ),
        ),
    ]
