# Generated by Django 5.0.14 on 2025-11-23 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_customerrow_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت تسجيل الدخول"
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت تسجيل الخروج"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="مفتاح الجلسة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة تسجيل الدخول",
                "verbose_name_plural": "جلسات تسجيل الدخول",
                "ordering": ["-login_time"],
            },
        ),
    ]
